#Variables file contains variables which are used in multiple files
configFilePath = "../config.ini"
maxFileSize = None
maxThreads = None
tempFolderPath = None
timeSlice = None
logLevel = None
logger = None
jobThread = None #Keeping it here in case we need to access the job runner later on in multiple files
listenerThread = None 
listenPort = None
sendPort = None
socketBufferSize = None
socketRecordNA = "400"
appname = None
jobURLList = []
bootstrapNodes = None
connectedNodes = []
connectedNodeLock = False